// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZl5lXY19PdnkAKRtZDMbRh2FjSnjFR4U',
    appId: '1:144718166492:web:e9e324e38e5f7b5bd13719',
    messagingSenderId: '144718166492',
    projectId: 'flutter-for-wordpress',
    authDomain: 'flutter-for-wordpress.firebaseapp.com',
    storageBucket: 'flutter-for-wordpress.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACf1lhsAh3E7JQpGwK2mnV4ef7Ozv7ws8',
    appId: '1:144718166492:android:73f0cd2cfdeeb75cd13719',
    messagingSenderId: '144718166492',
    projectId: 'flutter-for-wordpress',
    storageBucket: 'flutter-for-wordpress.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSONDCnI2aTz3OiBHhMpiTIZa0aMCGh9M',
    appId: '1:144718166492:ios:75b94412d5589fb8d13719',
    messagingSenderId: '144718166492',
    projectId: 'flutter-for-wordpress',
    storageBucket: 'flutter-for-wordpress.appspot.com',
    androidClientId: '144718166492-8aueltuds03rc2mgkbvsu71cmk67t51k.apps.googleusercontent.com',
    iosClientId: '144718166492-litnu5r49dhl4ubauem4ah1okqrkv394.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWordpressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSONDCnI2aTz3OiBHhMpiTIZa0aMCGh9M',
    appId: '1:144718166492:ios:e1d99e4bddff3748d13719',
    messagingSenderId: '144718166492',
    projectId: 'flutter-for-wordpress',
    storageBucket: 'flutter-for-wordpress.appspot.com',
    androidClientId: '144718166492-8aueltuds03rc2mgkbvsu71cmk67t51k.apps.googleusercontent.com',
    iosClientId: '144718166492-ptqflito9u26p08ukc961ua62noil9ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterForWordpressApp',
  );
}
